### ISSUE TITLE
initial pitch setting in navit tag not working

### ISSUE THREAD

**Issue by dbemowsk** [navit-gps/navit#1135] opened 2021-08-14 17:50 UTC
I am running a raspbery PI 4B 2GB running navit-git 0.5.3 installed from apt-get (found in About Navit). I am running Debian based Raspbeery Pi OS released 2021-05-07 locale EN_US.

When I try to set a pitch in the navit tag, the map shows vertically flipped showing a horizon.  This happens no matter the pitch I select , > 0 of course.  The attached image shows the inverted screen with the horizon.  I get this same view using any pitch greater than 0.  If I change the pitch value using an OSD button tag it works fine, but I want to set the initial view to 3D, but can't.  

I hope I got all the information you need.  If not please let me know.

![navit_pitch_problem](https://user-images.githubusercontent.com/2935181/129455917-ac22e2b0-c9d2-4194-b957-b02c89e3eab0.jpg)

**Comment by dbemowsk** [comment] 2021-08-14 17:54
This is the 2D view for the image above.  You should be able to make out the inversion of the map.

![navit_pitch_problem-2](https://user-images.githubusercontent.com/2935181/129456079-aa98d0ea-22f4-4dfa-ab11-917c71297a88.jpg)

**Comment by OLFDB** [comment] 2021-08-28 09:26
For the forum issue I can't help you. 

The pitch issue is specific to the Raspberry Pi release. I had used Raspbian Desktop to reproduce it first.
Now I have installed it on a Pi3 and can reproduce it with the Debian package installed by apt.

As I don't have the sources for the apt packet available, I debugged using Debian desktop.

For a build from trunk the pitch value set during startup is not transformed correctly as the values for the screen size are not set yet, when the pitch value gets set.

After startup when using the button the screen size is set in navit object and the transform value is calculated correctly. That explains, why you can set the pitch correctly via the UI button.

w and h in navit object are not explicitly initialized. In my build they are initialized to 0. Maybe the compiler used to build the Raspberry navit binary is not initializing uninitialized variables to 0 by default and that is creating the mirrored view?

I have also found that in gui_internal.c there is the attr_pitch handled, but that should be part of the navit tag and not the gui tag. The value is stored and read, but never used elsewhere in the gui_internal code.


Possible fix:

```
diff --git a/navit/navit.c b/navit/navit.c
index 5248e10ea..6cbf7cb1b 100644
--- a/navit/navit.c
+++ b/navit/navit.c
@@ -462,8 +462,27 @@ void navit_handle_resize(struct navit *this_, int w, int h) {
     int callback=(this_->ready == 1);
     this_->ready |= 2;
     memset(&sel, 0, sizeof(sel));
+    int firstcall = 0;
+    struct attr attr;
+
+    /* Fix for #1135: Check if pitch was set while w and h were 0. In this case set pitch
+     * again so transformation value is set correctly */
+    if(this_->w==0 && this_->h==0) {
+        firstcall=1;
+    }
+
     this_->w=w;
     this_->h=h;
+
+    /* Fix for #1135: Now w and h are set initially, we can set pitch value again
+     *
+     */
+    if(firstcall) {
+        attr.type=attr_pitch;
+        attr.u.num=this_->pitch;
+        navit_set_attr(this_, &attr); // Set pitch again
+    }
+
```

**Comment by dbemowsk** [comment] 2021-08-28 16:28
So is there a way I can fix this on my build?  Can I compile a new version from a source?  If so, where do I get that source and what do I need to do it?

**Comment by OLFDB** [comment] 2021-08-28 16:54
Take a look at https://navit.readthedocs.io/en/v0.5.6/development/linux_development.html#build-dependencies

Install the Debian dependencies and get the sources using git.
Apply the patch to navit.c and build the binary.

**Comment by jkoan** [comment] 2021-08-28 18:30
Or just use the binary from here: https://1745-171751732-gh.circle-artifacts.com/0/linux/_CPack_Packages/Linux/TGZ/navit.tar.gz

**Comment by dbemowsk** [comment] 2021-08-28 19:45
@jkoan is that binary for the Raspberry Pi?

**Comment by jkoan** [comment] 2021-08-28 20:07
> @jkoan is that binary for the Raspberry Pi?

Oh sorry, no, my bad

**Comment by dbemowsk** [comment] 2021-08-28 20:11
@jkoan do you know of an updated binary for the raspberry?

**Comment by dbemowsk** [comment] 2021-08-29 01:21
@OLFDB so after compiling navit and trying to run it, I get errors.  After compiling it in ~/navit-build I renamed the executable in /usr/bin/navit to /usr/bin/navit-bak.  I then copied the newly compiled navit executable to /usr/bin/navit.  I went to a terminal window and changed directory to /usr/bin and then ran ./navit and this is what I get.

error:navit:plugins_init:Warning: No plugins found. Is Navit installed correctly?
error:navit:map_new:invalid type 'textfile'
error:navit:graphics_new:Failed to load graphics plugin gtk_drawing_area.
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'navigation_next_turn'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'speed_warner'
error:navit:osd_new:invalid OSD type 'text'
error:navit:osd_new:invalid OSD type 'gps_status'
error:navit:osd_new:invalid OSD type 'button'
error:navit:osd_new:invalid OSD type 'scale'
error:navit:osd_new:invalid OSD type 'button'
error:navit:osd_new:invalid OSD type 'button'
error:navit:osd_new:invalid OSD type 'cmd_interface'
error:navit:osd_new:invalid OSD type 'button'
error:navit:osd_new:invalid OSD type 'cmd_interface'
error:navit:osd_new:invalid OSD type 'button'
error:navit:osd_new:invalid OSD type 'compass'
error:navit:vehicle_new:invalid source 'gpsd://localhost': unknown type 'gpsd'
error:navit:speech_new:wrong type 'cmdline'
error:navit:xinclude:Unable to include '/usr/local/share/navit/maps/*.xml'
error:navit:map_new:invalid type 'binfile'
error:navit:navit_init:FATAL: No GUI available.

Not sure what I missed in the build.  Any ideas?  I am guessing I don't have some of the libraries installed for compiling, but not exactly sure because I don't build from source code much.

**Comment by OLFDB** [comment] 2021-08-29 05:02
navit has a lot of libraries e.g. for the graphics and vehicle (gps sources). Those seem to be missing now.
Did you install your build using `make install` ?

If you build from source the installation directories are different from the ones used by the apt package.

apt dirs and dirs used by source build:
navit is in /usr/bin vs /usr/local/bin
libs are in /usr/lib/navit vs  /usr/local/lib/navit
shared folder /usr/share/navit vs  /usr/local/share/navit

You can install your build in parallel to the apt package. Just start /usr/local/bin/navit and you'll use the new binary.

**Comment by OLFDB** [comment] 2021-08-29 05:18
@jkoan You have closed it referencing the fix for #1130. #1136 is not merged yet.

**Comment by jkoan** [comment] 2021-08-29 07:13
> @jkoan You have closed it referencing the fix for #1130. #1136 is not merged yet.

Actually GitHub itself closed it because one of your commits stated that it fixed it. Probably you just created the branch from the other fixes branch. Ideally you would have created it again from trunk. But even if you didn't, instead of reverting you you'd have just rebased interactively to remove the wrong commit. But I can say even though I know what to do, I still have problems with git from time to time.
So no worries, I will reopen the issue ;)

**Comment by OLFDB** [comment] 2021-08-29 07:19
Thanks. Working with git is not one of my favorites... :-)

**Comment by dbemowsk** [comment] 2021-08-29 20:03
@OLFDB THANK YOU....After running make install as you suggested, I was able to get this to work.   I had to move some of my custom icon files that I downloaded, but it works.  I can also, as you said, run the apt version as it is installed in a different location.

THANK YOU AGAIN.

**Closed** 2021-08-31 10:15 UTC
