### ISSUE TITLE
Maptool: Endless Loop on Phase 9 (generating multipolygons)

### ISSUE THREAD

**Issue by jkoan** [navit-gps/navit#1128] opened 2021-07-14 13:24 UTC
When Running maptool against the osm.pbf file attached below the Process keeps hanging and does only print the alarm info messages any 30secs 

## Expected Behavior
Maptool should continue and finish the Phase

## Current Behavior

Runs in endless loop

## Steps to Reproduce
[greenland-latest.osm.pbf.gz](https://github.com/navit-gps/navit/files/6816091/greenland-latest.osm.pbf.gz)
[Log from Gtihub Actions](https://github.com/navit-gps/navit/files/6816127/PROGRESS9_greenland.txt)
[Log from my machine](https://github.com/navit-gps/navit/files/6816134/maptool_phase_9_loop.txt)

1. Download greenland-latest.osm.pbf.gz from above
2. Gunzip the file
3. Run the Command like normal: `maptool --protobuf -i ~/Downloads/greenland-latest.osm.pbf ~/Downloads/greenland-latest.bin`
4. Wait untill "PROGRESS9: Processed 200 nodes (195 out) 0 ways 4185 relations 0 tiles" apperes multiple times

## Context (Environment)
Github Actions: Standart ubuntu-latest runner
PC: AMD Ryzen 2600 CPU; NVMe SSD; Manjaro Linux OS

## Comment
Probably @metalstrolch could help here?

**Comment by metalstrolch** [comment] 2021-07-14 13:56
Well... I need to deeper investigate what exactly happens, but on first view in both github actions and local run worker thread "4" does not finish making the main thread wait for ever. That never happened to me, but I'm mostly processing full planet. I'll try to debug if this is reproducible on my box.

**Comment by metalstrolch** [comment] 2021-07-14 13:57
Can you retry with -T 1  in the meantime? This should limit the number of worker threads to 1. Shouldn't make much difference for Greenland as Greenland is quite smallish.

**Comment by jkoan** [comment] 2021-07-14 15:30
`-T 1` results in the same Behavior: [maptool_phase_9_loop_-T_1.txt](https://github.com/navit-gps/navit/files/6817203/maptool_phase_9_loop_-T_1.txt)
 
I also debugged the Problem and it seems like its stuck in a loop within those lines:
https://github.com/navit-gps/navit/blob/ea5a86beafcb52f54544e079ef7e4f8ac8b070f4/navit/maptool/osm.c#L2384-L2387

**Comment by metalstrolch** [comment] 2021-07-14 19:48
Umm, I have the feeling maptool is doing right, but the OSM data got really complex recently.

It "stalls" at OSM relation ID 9488835 which was added recently to OSM. This one has 24960 member ways! It clearly outrules Aegyptian's lake nasser as one of the biggest OSM relation so far. So I assume to convert this it may take some time.
Stay tuned if this turns out to be true.

**Comment by metalstrolch** [comment] 2021-07-14 22:21
Ok, I was right. It finishes after around 2.5h on my machine (CoreI3, 3rd gen). So this is not a "bug". Be patient, and it finishes.

Fun fact is the resulting polygon of relation ID 9488835 doesn't even result in a viewable polygon in binfile, as its's tag do not result in any known type of Navit causing maptool to filter it out if -n is given. So converting it is quite useless.

It cannot be "solved" that processing huge multipolyons takes a lot of time. However I'll try to make "-n" parameter filter out multipolygons of "unknown" types before processing them so we at least do not process useless ones.

**Comment by metalstrolch** [comment] 2021-07-14 23:12
See #1129 which would filter out relation 9488835 since it will only give "street_unknown" binfile type if you give -n on command line.

**Comment by metalstrolch** [comment] 2021-09-01 18:55
Closing this as it was indeed no bug.

**Closed by metalstrolch** 2021-09-01 18:55 UTC
