### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [navit-gps/navit#436] opened 2018-04-11 06:40 UTC
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by jkoan** [comment] 2018-04-11 13:02
Hi @redmusic27,
thanke you for your offer, i think we would really like to have a new and up to date logo.
Our current logo looks like this:
![1024px-navit_logo svg](https://user-images.githubusercontent.com/3747958/38617975-a546c1d8-3d98-11e8-8348-6a02f604e1f4.png)

And our app Icon on Android looks like this:
![icon](https://user-images.githubusercontent.com/3747958/38618092-ec9b21f0-3d98-11e8-9752-8454800b20f4.png)

Feel free to ask any question you need to :)

Many thx in advance
Regards Jkoan

**Comment by redmusic27** [comment] 2018-04-12 17:08
Hello sir @jkoan , I have created a concept logo for you. If you like it, I'll send you all files and pr.
Is there anything you want ?

**Concept**
![concept](https://user-images.githubusercontent.com/37577374/38692611-7b000314-3eae-11e8-8909-2b7dc8600d2a.jpg)
**Horizontal**
![horizontal](https://user-images.githubusercontent.com/37577374/38692618-7ef3df04-3eae-11e8-8adb-866b8c07a56a.jpg)
**Vertical**
![vertical](https://user-images.githubusercontent.com/37577374/38692621-812f262a-3eae-11e8-9916-75ebd411da0e.jpg)

**Comment by hoehnp** [comment] 2018-04-12 20:36
Thanks for picking up the work. A new logo would be really nice. Also I like the idea of a kind of compass shape. Only criticism from my side is that intuitively I would not recognize center symbol as the characteristic "N" of navit.

**Comment by zintor** [comment] 2018-04-14 21:13
Nice to see the work on a new logo.
I also like the compass shape, but also agree with hoehnp: The "N" is not easy to recognize. Could you try to highlight the "N" inside the compass?

**Comment by hoehnp** [comment] 2018-04-16 15:10
Looks great. I like it a lot better.

**Comment by jkoan** [comment] 2018-04-16 15:32
Hi @redmusic27,
i also really much like the second logo you posted, only one question, is it possible to have the red corner of the icon the same as the blue one?

![navit_new_logo](https://user-images.githubusercontent.com/3747958/38819606-1d90ce52-419c-11e8-9871-39608a98d901.png)

**Comment by redmusic27** [comment] 2018-04-16 15:35
Thank you, of course you can. I will change it now sir

**Comment by redmusic27** [comment] 2018-04-16 15:43
Like this sir? if it is okay i will prepare all files along with pr him immediately
![image](https://user-images.githubusercontent.com/37577374/38820215-7353c83c-41c7-11e8-865d-211406075709.png)

**Comment by jkoan** [comment] 2018-04-16 15:46
I really much like it like this particularly with the colors in the last one. But lets wait for the other opinions from the team. If you would like you could prepare the PR then we can vote on that.

**Comment by redmusic27** [comment] 2018-04-16 15:49
So? i immediately make pr or how sir?

**Comment by jkoan** [comment] 2018-04-16 15:52
If nobody is completely against the logo tomorrow would be grate so other team members can join the discussion.

**Comment by redmusic27** [comment] 2018-04-16 15:53
Okay thanks sir, I will prepare it for tomorrow

**Comment by redmusic27** [comment] 2018-04-16 16:13
* LOGOMARK *
![logomark-main](https://user-images.githubusercontent.com/37577374/38821599-3784d1c6-41cb-11e8-9169-8abed48c8ff6.png)
![logomark-black](https://user-images.githubusercontent.com/37577374/38821598-3748020a-41cb-11e8-8706-c57566f3a229.png)
![logomark-white](https://user-images.githubusercontent.com/37577374/38821600-37c43abe-41cb-11e8-98ed-638845e1d256.png)

* LOGOTYPE HORIZONTAL *
![horizontal-main](https://user-images.githubusercontent.com/37577374/38821625-4a804bac-41cb-11e8-93c3-7d896de4f424.png)
![horizontal-black](https://user-images.githubusercontent.com/37577374/38821623-4a3cc44a-41cb-11e8-913d-ad3561d3ae4e.png)
![horizontal-white](https://user-images.githubusercontent.com/37577374/38821626-4abd6f50-41cb-11e8-8398-78b7cb7ed207.png)

* LOGOTYPE VERTICAL *
![vertical-main](https://user-images.githubusercontent.com/37577374/38821651-56cdd0aa-41cb-11e8-9d89-d307fc7e905c.png)
![vertical-black](https://user-images.githubusercontent.com/37577374/38821649-569247c4-41cb-11e8-8056-2d666e2cbab4.png)
![vertical-white](https://user-images.githubusercontent.com/37577374/38821652-57096548-41cb-11e8-9e01-df7b166820d8.png)

* ICON *
![icon-main](https://user-images.githubusercontent.com/37577374/38821663-6024ef6c-41cb-11e8-968a-4ea861532027.png)
![icon-main-2](https://user-images.githubusercontent.com/37577374/38821664-606181de-41cb-11e8-874e-bfdb3732ca84.png)
![icon-main-3](https://user-images.githubusercontent.com/37577374/38821665-609b7e8e-41cb-11e8-81f7-690f7bf20bc6.png)
![icon-black](https://user-images.githubusercontent.com/37577374/38821662-5fe8d810-41cb-11e8-9f13-037d99ac92eb.png)
![icon-white](https://user-images.githubusercontent.com/37577374/38821666-60d57b66-41cb-11e8-9aaa-57ffa28a4f33.png)

**Comment by redmusic27** [comment] 2018-04-16 16:24
Thanks a lot sir @pgrandin ,For text I use the available fonts that is "Arial Bold"

**Comment by hoehnp** [comment] 2018-04-16 21:27
Thanks a lot @redmusic27. Very good work.

**Comment by zintor** [comment] 2018-04-17 12:03
Thx @redmusic27! Looks nearly good to me. "Nearly" because in my eyes, the "N" in the compass should be more bold. Like in the text "Navit". 

![navit](https://user-images.githubusercontent.com/22443449/38868619-ed4bb17e-4247-11e8-98c2-8fff6b8cbebe.jpg)

What do you/the others think?

**Comment by mvglasow** [comment] 2018-04-17 17:33
The bolder N looks indeed better.

I would also suggest revisiting the text font used. Arial has seen such widespread usage, including in many poorly typeset documents, that I would suggest a different sans-serif font, preferably a FOSS one. Some FOSS options include:

* [Fira](https://en.wikipedia.org/wiki/Fira_Sans) (the Mozilla typeface)
* Nimbus Sans (a Helvetica lookalike)
* [M+](https://en.wikipedia.org/wiki/M%2B_FONTS)
* [Noto](https://en.wikipedia.org/wiki/Noto_fonts) (based on Droid, the former Android UI font, with some differences)
* [Overpass](https://en.wikipedia.org/wiki/Overpass_(typeface)) (the US traffic sign typeface)
* [PT Sans](https://en.wikipedia.org/wiki/PT_Fonts)
* Roboto (the default UI font on Android)
* Ubuntu (the UI font for Ubuntu)
* [Source Sans Pro](https://en.wikipedia.org/wiki/Source_Sans_Pro)

My personal favorites include PT Sans, M+ and Overpass. They are unobtrusive, yet distinct. The first two are not overly ubiquitous, while Overpass has the association with traffic.

**Comment by mvglasow** [comment] 2018-04-19 17:39
Some samples with the logo fonts I mentioned above:

![navit logo samples](https://user-images.githubusercontent.com/2377496/39008362-c921b3bc-4408-11e8-9a3b-2964e6b90c2f.png)

Looking at these, my favorite is Overpass Heavy, second would be Source Sans Pro Bold.

**Comment by zintor** [comment] 2018-05-01 21:31
@redmusic27: Could you please make some logos with the bolder "N" in the logo with the fonts "Overpass Heavy" and "Source Sans Pro Bold". It would be nice to compare these two fonts in the logo and text.

**Comment by jkoan** [comment] 2018-05-28 05:53
@redmusic27 is the offer still valid?

**Comment by jkoan** [comment] 2018-06-07 19:55
@redmusic27 I/We really like the work you did and we are so close to the goal :(

**Comment by jkoan** [comment] 2018-08-21 17:17
@redmusic27 it would be nice if you could give us a status update :(

**Comment by lains** [comment] 2018-09-01 15:11
It seems @redmusic27's activity has reduced to almost zero lot since 11th April.
Let's hope nothing bad happened to him/her.
How shall we move forward?
Is a re-implementation of the last logo proposal, as SVG, in B/W a good starting point (based on @zintor's last proposal above)?
Is there anyone that could undertake this work?

**Comment by zintor** [comment] 2018-10-08 20:42
I vectorized the bitmap and created it with the fonts:
Overpass Heavy: 

![navit_new_overpass](https://user-images.githubusercontent.com/22443449/46632523-46772800-cb4b-11e8-8c70-82f8e4404224.png)

Source Sans Pro Bold: 

![navit_new_sourcesanspro](https://user-images.githubusercontent.com/22443449/46632583-6f97b880-cb4b-11e8-8a34-b88dea6fa932.png)

**Comment by lains** [comment] 2018-10-10 10:12
Great! As far as I'm concerned, I like even better the second (bold) version.

**Comment by mvglasow** [comment] 2018-10-11 21:07
Looks good! I’m not particularly picky about the N in the compass logo, most sans-serif fonts with the appropriate weight would work here. My earlier comment was primarily aimed at the text in the logotype—I realize this might not have come out clearly.

**Comment by zintor** [comment] 2018-10-26 20:18
What do you think of this:

![logos](https://user-images.githubusercontent.com/22443449/47590585-f8e12480-d96c-11e8-84f2-7e17b9ee12b3.png)

![example1](https://user-images.githubusercontent.com/22443449/47590592-04cce680-d96d-11e8-99ae-2406d6e53fd4.png)

![example2](https://user-images.githubusercontent.com/22443449/47590595-0696aa00-d96d-11e8-8900-c669c1730f77.png)

**Comment by lains** [comment] 2018-10-29 06:50
Looks nice!
Just one note on the very close proximity of the left and right sides of the N and the circle, which may make the N less readable.
In your previous proposal, I think there was more space (actually only on the left handside).

**Comment by zintor** [comment] 2018-10-31 19:14
You are right. It was more space. I tried the smallest letter size, which fits the best without any strectching:
![logos2](https://user-images.githubusercontent.com/22443449/47812088-b5f5c700-dd47-11e8-9f73-79e3b80f20db.png)
![example3](https://user-images.githubusercontent.com/22443449/47812741-7def8380-dd49-11e8-9f41-12ead9d5a211.png)

**Comment by lains** [comment] 2018-11-10 09:50
Very nice to me. Thanks for this nice work!
Does anyone else has other comments?

**Comment by hoehnp** [comment] 2018-11-10 11:54
I also like it a lot. Looks very good.

**Comment by lains** [comment] 2018-11-19 20:52
Shall we go on and open a PR to use this new logo in the application?

**Comment by zintor** [comment] 2018-11-19 21:55
I created a [wiki site](https://wiki.navit-project.org/index.php/Logo) for the logo.
There we could summarize all the logo discussion, color codes, shapes and where the logo is used.

**Comment by lains** [comment] 2018-11-29 05:51
@zintor, do you have the SVG version of these logos?
I will try to integrate them in the code and build process, so that a pull request can be opened to propose this change.

**Comment by lains** [comment] 2018-11-30 20:12
Thanks @zintor.

I am getting the main 'N' slightly shifted when I open it using Inkscape:
![bitmap](https://user-images.githubusercontent.com/383502/49311383-4fe49700-f4e1-11e8-91c5-5f811bad7238.png)

I did some re-alignment and I reduced the 'N' to roughty 90%.
Here is what I get:
![bitmap](https://user-images.githubusercontent.com/383502/49311749-4dcf0800-f4e2-11e8-8cef-83da197d338f.png)

This is maybe because of the font `font-family:'Source Sans Pro'` that is referred to inside the svg... it seems the font I am getting is not the same as the one that was used in your samples above.
And maybe also it now displays properly on my machine, but it could be shifted again on someone else...

[navit_new_vec_v2.zip](https://github.com/navit-gps/navit/files/2634837/navit_new_vec_v2.zip)

**Comment by lains** [comment] 2018-12-16 11:19
I gave it a try on using this new logo also on the internal GUI menu.
The issue is that the N is actually not transparent (while the circle around it is), but is has a fixed color (white on my svg):
![navit_with_new_logo](https://user-images.githubusercontent.com/383502/50052922-73881e00-012c-11e9-979d-c1692a455578.png)

Is there any way to fix this other than changing the SVG to use black color for letter 'N'?

**Comment by zintor** [comment] 2018-12-16 19:54
@lains: you could cut-out the "N" from the inner circle.
I've done it here: 
[navit_new_vec_differnce.zip](https://github.com/navit-gps/navit/files/2683906/navit_new_vec_differnce.zip)

**Comment by lains** [comment] 2018-12-30 15:32
Here is a screenshot for the new logo used as Action icon in the internal GUI:
![navit_new_transp](https://user-images.githubusercontent.com/383502/50548555-4fa9f980-0c4f-11e9-8d92-d24cfc021cc9.png)

And as an icon inside the About menu (I think the icon in use should be bigger):
![navit_new_about_transp](https://user-images.githubusercontent.com/383502/50548580-afa0a000-0c4f-11e9-9f41-7cde3daef8e7.png)

I have used the top left logo in the [provided svg file](https://github.com/navit-gps/navit/files/2683906/navit_new_vec_differnce.zip).

Duplicate logos also appear here in the repo:
https://github.com/navit-gps/navit/blob/trunk/navit/gui/qt5_qml/skins/modern/navit.svg
https://github.com/navit-gps/navit/blob/trunk/navit/gui/qt5_qml/skins/modern/navit.svg

These could probably be updated to only be links to the main navit.svg icon.

Also, it seems the gtk GUI window icon is not using the navit logo, this could also be changed to point to the same logo again.

**Comment by lains** [comment] 2018-12-30 21:30
New logo pack (with vectorial N, centered in all logos, instead of font)
[navit_logo_full_vect_no_font.zip](https://github.com/navit-gps/navit/files/2717532/navit_logo_full_vect_no_font.zip)

**Comment by lains** [comment] 2019-09-25 08:59
Closing as PR#724 has been merge.

**Closed by lains** 2019-09-25 08:59 UTC
Labels: icons, proposal
